# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4b6544e24207f353da2abd17eaf204999a0a206e98e6a31f70f1d8f6663042ef10395f4e9f43c5d36c167ee4dd4e947fa7fe1bbf0f4ae9fc61288f78f861da

test:
  secret_key_base: 63fe9695891faca9d4e267e2c75e5b5d773c0fcf28c3b26a29fa503bdcff77b7b969ec97e1050b173b9db77cc9fe857b49e6591fe965903c448544db5b05a2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
